// <auto-generated>
// Generated by tools/generate-cdp-bindings.ps1 from contracts/cdp-bindings-subset.json.
// Regenerate; do not edit by hand.
// </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace StealthEye.Worker;

internal static class CdpMethods
{
    internal const string PageEnable = "Page.enable";
    internal const string PageNavigate = "Page.navigate";
    internal const string PageGetFrameTree = "Page.getFrameTree";
    internal const string PageFrameNavigated = "Page.frameNavigated";
    internal const string RuntimeEvaluate = "Runtime.evaluate";
    internal const string DomGetDocument = "DOM.getDocument";
    internal const string BrowserSetDownloadBehavior = "Browser.setDownloadBehavior";
    internal const string BrowserDownloadWillBegin = "Browser.downloadWillBegin";
    internal const string BrowserDownloadProgress = "Browser.downloadProgress";
}

internal sealed record CdpEmptyRequest;

internal sealed record CdpPageNavigateRequest(
    [property: JsonPropertyName("url")] string Url);

internal sealed record CdpPageNavigateResult(
    [property: JsonPropertyName("frameId")] string? FrameId,
    [property: JsonPropertyName("loaderId")] string? LoaderId,
    [property: JsonPropertyName("errorText")] string? ErrorText);

internal sealed record CdpRuntimeEvaluateRequest(
    [property: JsonPropertyName("expression")] string Expression,
    [property: JsonPropertyName("returnByValue")] bool ReturnByValue,
    [property: JsonPropertyName("awaitPromise")] bool AwaitPromise);

internal sealed record CdpDomGetDocumentRequest(
    [property: JsonPropertyName("depth")] int Depth,
    [property: JsonPropertyName("pierce")] bool Pierce);

internal sealed record CdpDomGetDocumentResult(
    [property: JsonPropertyName("root")] CdpDomNode Root);

internal sealed record CdpDomNode(
    [property: JsonPropertyName("nodeId")] int NodeId,
    [property: JsonPropertyName("backendNodeId")] int BackendNodeId,
    [property: JsonPropertyName("nodeType")] int NodeType,
    [property: JsonPropertyName("nodeName")] string NodeName,
    [property: JsonPropertyName("nodeValue")] string NodeValue,
    [property: JsonPropertyName("frameId")] string? FrameId,
    [property: JsonPropertyName("attributes")] string[]? Attributes,
    [property: JsonPropertyName("children")] CdpDomNode[]? Children);

internal sealed record CdpPageGetFrameTreeResult(
    [property: JsonPropertyName("frameTree")] CdpFrameTree FrameTree);

internal sealed record CdpFrameTree(
    [property: JsonPropertyName("frame")] CdpFrame Frame,
    [property: JsonPropertyName("childFrames")] CdpFrameTree[]? ChildFrames);

internal sealed record CdpFrame(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("parentId")] string? ParentId,
    [property: JsonPropertyName("loaderId")] string? LoaderId,
    [property: JsonPropertyName("url")] string Url);

internal sealed record CdpPageFrameNavigatedEvent(
    [property: JsonPropertyName("frame")] CdpFrame Frame);

internal sealed record CdpBrowserSetDownloadBehaviorRequest(
    [property: JsonPropertyName("behavior")] string Behavior,
    [property: JsonPropertyName("downloadPath")] string DownloadPath,
    [property: JsonPropertyName("eventsEnabled")] bool EventsEnabled);

internal sealed record CdpBrowserDownloadWillBeginEvent(
    [property: JsonPropertyName("frameId")] string FrameId,
    [property: JsonPropertyName("guid")] string Guid,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("suggestedFilename")] string SuggestedFilename);

internal sealed record CdpBrowserDownloadProgressEvent(
    [property: JsonPropertyName("guid")] string Guid,
    [property: JsonPropertyName("totalBytes")] double TotalBytes,
    [property: JsonPropertyName("receivedBytes")] double ReceivedBytes,
    [property: JsonPropertyName("state")] string State,
    [property: JsonPropertyName("filePath")] string? FilePath);

internal sealed record CdpRuntimeEvaluateResult(
    [property: JsonPropertyName("result")] JsonElement Result,
    [property: JsonPropertyName("exceptionDetails")] JsonElement? ExceptionDetails);
