param(
    [string]$SpecPath = (Join-Path $PSScriptRoot '..\contracts\cdp-bindings-subset.json'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\src\Eye.Worker\BrowserCdpBindings.Generated.cs')
)

$ErrorActionPreference = 'Stop'
$spec = Get-Content $SpecPath -Raw | ConvertFrom-Json
$q = [char]34
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add('// <auto-generated>')
$lines.Add('// Generated by tools/generate-cdp-bindings.ps1 from contracts/cdp-bindings-subset.json.')
$lines.Add('// Regenerate; do not edit by hand.')
$lines.Add('// </auto-generated>')
$lines.Add('#nullable enable')
$lines.Add('using System.Text.Json;')
$lines.Add('using System.Text.Json.Serialization;')
$lines.Add('')
$lines.Add('namespace ' + $spec.namespace + ';')
$lines.Add('')
$lines.Add('internal static class CdpMethods')
$lines.Add('{')
foreach ($method in $spec.methods) {
    $lines.Add('    internal const string ' + $method.constant + ' = ' + $q + $method.value + $q + ';')
}
$lines.Add('}')
$lines.Add('')

foreach ($record in $spec.records) {
    $properties = @($record.properties)
    if ($properties.Count -eq 0) {
        $lines.Add('internal sealed record ' + $record.name + ';')
        $lines.Add('')
        continue
    }

    $lines.Add('internal sealed record ' + $record.name + '(')
    for ($i = 0; $i -lt $properties.Count; $i++) {
        $property = $properties[$i]
        $suffix = if ($i -eq $properties.Count - 1) { ');' } else { ',' }
        $lines.Add(
            '    [property: JsonPropertyName(' + $q + $property.json + $q + ')] ' +
            $property.cs_type + ' ' + $property.cs_name + $suffix)
    }
    $lines.Add('')
}

$parent = Split-Path -Parent $OutputPath
if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
[IO.File]::WriteAllText(
    [IO.Path]::GetFullPath($OutputPath),
    ($lines -join [Environment]::NewLine),
    [Text.UTF8Encoding]::new($false))
